"use client"; // ADD THIS LINE AT THE TOP

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoutButton } from "../components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Remove or comment out metadata for now
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>NVH Agri CRM</title>
        <meta name="description" content="NVH Agri CRM System" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-slate-900 text-slate-50 border-b border-slate-800">
          <div className="max-w-5xl mx-auto flex items-center justify-between px-4 py-2 text-xs">
            <span className="font-semibold">NVH Agri CRM</span>
            <LogoutButton />
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}